# Global options:

[mypy]
warn_unused_configs = True
follow_imports = silent
show_error_context = True
namespace_packages = True
strict = True
files =
    numba_scfg
exclude =
    numba_scfg/tests|conf.py

# graphviz is an untyped third-party package with no stubs available.
[mypy-graphviz]
ignore_missing_imports = True
